name: Deploy to StableHost
on:
  push:
    branches:
      - master # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          source: "./*,!.git,!.github"
          target: "/home/${{ secrets.SSH_USER }}/public_html"
